# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapBranding
                                 A QGIS plugin
 Export the current QGIS map view with a logo, scale bar, north arrow, and metadata footer (project name, date, CRS).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-30
        copyright            : (C) 2025 by Mikhail Sokolov
        email                : sokolov.usmk@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapBranding class from file MapBranding.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_branding import MapBranding
    return MapBranding(iface)
