# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapBranding
                                 A QGIS plugin
 Export the current QGIS map view with a logo, scale bar, north arrow, and metadata footer (project name, date, CRS).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-30
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Mikhail Sokolov
        email                : sokolov.usmk@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path

# Qt (via QGIS’ PyQt shim)
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import (
    Qt, QTimer, QSettings, QTranslator, QCoreApplication,
    QSize, QRectF, QEvent, QDir, QSignalBlocker
)
from qgis.PyQt.QtGui import (
    QIcon, QPixmap, QPainter, QColor, QImage
)
from qgis.PyQt.QtWidgets import (
    QAction, QFileDialog, QMessageBox, QMenu, QToolButton, QVBoxLayout, QLabel
)
from qgis.PyQt.QtSvg import QSvgRenderer

# QGIS core
from qgis.core import (
    QgsApplication, QgsMapSettings, QgsMapRendererParallelJob,
    QgsRectangle, QgsProject, QgsUnitTypes
)

from .map_branding_dialog import MapBrandingDialog
from .extent_picker_tool import ExtentPickerTool


class MapBranding:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'MapBranding_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Map Branding')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # Set default SVG paths to bundled resources:
        self._north_arrow_svg_path = None
        self._northPreviewLabel = None
        self._arrowPreviewTarget = None
        self._north_arrow_scale_pct = 18  # % of shorter preview side (default size)
        self._north_arrow_position = "Top Left"

        # Scale bar config
        self._scale_bar_style = None  # comboScaleBar
        self._scale_bar_units_mode = "Project"  # comboScaleUnits
        self._scale_bar_segments_left = 2  # spinScaleSegmentsLeft
        self._scale_bar_segments_right = 2  # spinScaleSegmentsRight
        self._scale_bar_position = "Bottom Left"  # via radio buttons

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MapBranding', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/map_branding/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Brand current QGIS view'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Map Branding'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = MapBrandingDialog()
            self._populate_north_arrows_dropdown()
            # 1) Grab your pre-made widget from the UI
            self._arrowPreviewTarget = getattr(self.dlg, "arrowWidget", None)

            # 2) Create or reuse a QLabel inside it for rendering
            if self._arrowPreviewTarget is not None:
                if isinstance(self._arrowPreviewTarget, QLabel):
                    # arrowWidget is already a QLabel — use it directly
                    self._northPreviewLabel = self._arrowPreviewTarget
                else:
                    # arrowWidget is a generic QWidget — add a QLabel inside
                    if self._arrowPreviewTarget.layout() is None:
                        self._arrowPreviewTarget.setLayout(QVBoxLayout(self._arrowPreviewTarget))
                    self._northPreviewLabel = QLabel(self._arrowPreviewTarget)
                    self._arrowPreviewLabel = self._northPreviewLabel  # optional alias if you used this name before
                    self._northPreviewLabel.setAlignment(Qt.AlignCenter)
                    self._northPreviewLabel.setStyleSheet("QLabel { border: 1px solid #aaa; background: transparent; }")
                    self._arrowPreviewTarget.layout().addWidget(self._northPreviewLabel)

                # optional: a sensible minimum
                self._northPreviewLabel.setMinimumSize(72, 72)
                self._northPreviewLabel.setScaledContents(False)  # we render at exact size, no QLabel scaling

                # Re-render on container resize
                self._arrowPreviewTarget.installEventFilter(self.dlg)

            # 3) Connect the combo to update the preview
            combo = getattr(self.dlg, "comboNorthArrowStyle", None)
            if combo is not None:
                combo.currentIndexChanged.connect(self._on_north_arrow_style_changed)

            # 4) Initial render
            self._update_north_arrow_preview()

            self.dlg.comboNorthArrowStyle.currentIndexChanged.connect(self._on_north_arrow_style_changed)
            self.dlg.comboNorthArrowPosition.currentIndexChanged.connect(self._on_north_arrow_position_changed)
            sl = getattr(self.dlg, "horizontalSliderArrowSize", None)
            if sl is not None:
                sl.setMinimum(5)  # sensible range: 5%..40% of the shorter side
                sl.setMaximum(40)
                sl.setSingleStep(1)
                sl.setValue(self._north_arrow_scale_pct)
                sl.valueChanged.connect(self._on_north_arrow_scale_changed)

            # ----- Scale bar UI wiring -----
            combo_scale = getattr(self.dlg, "comboScaleBar", None)
            if combo_scale is not None:
                combo_scale.clear()
                combo_scale.addItems(["None", "Single Box", "Double Box", "Line Ticks Middle"])
                combo_scale.setCurrentText(self._scale_bar_style)
                combo_scale.currentIndexChanged.connect(self._on_scale_bar_style_changed)

            combo_units = getattr(self.dlg, "comboScaleUnits", None)
            if combo_units is not None:
                combo_units.clear()
                combo_units.addItems(["Project", "m", "km", "ft", "mi"])
                combo_units.setCurrentText(self._scale_bar_units_mode)
                combo_units.currentIndexChanged.connect(self._on_scale_bar_units_changed)

            spin_left = getattr(self.dlg, "spinScaleSegmentsLeft", None)
            spin_right = getattr(self.dlg, "spinScaleSegmentsRight", None)
            if spin_left is not None:
                spin_left.setMinimum(1)
                spin_left.setValue(self._scale_bar_segments_left)
                spin_left.valueChanged.connect(self._on_scale_bar_segments_changed)
            if spin_right is not None:
                spin_right.setMinimum(0)
                spin_right.setValue(self._scale_bar_segments_right)
                spin_right.valueChanged.connect(self._on_scale_bar_segments_changed)

            self.dlg.comboScaleBarPosition.currentIndexChanged.connect(self._on_scale_bar_position_changed)
            cb = getattr(self.dlg, "sbWhiteBg", None)
            if cb is not None:
                cb.toggled.connect(lambda _checked: self._render_preview_current_extent())


        # Initialize dialog and set up the UI
        self.dlg.show()
        self._setup_choose_extent_menu()
        self._custom_extent = None  # QgsRectangle in project CRS, or None
        self.dlg.lineExtent.setPlaceholderText("xmin, ymin, xmax, ymax (project CRS)")
        self._initialize_size_scaler()

        # Connect buttons
        self.dlg.btnClose.clicked.connect(self._close)
        self.dlg.btnExport.clicked.connect(self._export)

        self.dlg.btnBrowseLogo.clicked.connect(self._browse_logo)
        self.dlg.btnClear.clicked.connect(lambda: self.dlg.lineLogoPath.clear())
        self.dlg.horizontalSlider.setToolTip("Logo opacity (0-100%)")
        self.dlg.sizeScaler.valueChanged.connect(self._change_width_height)
        self.dlg.spinWidth.valueChanged.connect(self._change_width)
        self.dlg.spinHeigth.valueChanged.connect(self._change_height)

        # Link self._custom_extent to QWidget:
        self._visualize_area_from_custom_extent()
        QTimer.singleShot(0, self._render_preview_current_extent)

    def _draw_scale_bar(self, img: QImage, content: QRectF, extent_width_map_units: float):
        """
        Draws the scale bar onto img inside 'content' (map content rect).
        Uses current style, units, segments, position, and optional white background (sbWhiteBg).
        """
        if self._scale_bar_style not in ("Single Box", "Double Box", "Line Ticks Middle"):
            return
        if content.width() <= 0 or content.height() <= 0 or extent_width_map_units <= 0:
            return

        total_segments = self._scale_bar_segments_left + self._scale_bar_segments_right
        if total_segments <= 0:
            return

        # Map resolution in map units per pixel
        mu_per_px = float(extent_width_map_units) / float(content.width())

        unit_factor, unit_label = self._scale_bar_unit_factor()
        if unit_factor <= 0:
            return

        # Display units per pixel
        du_per_px = mu_per_px * unit_factor

        # Max width of scale bar = 40% of content width
        max_px = content.width() * 0.4

        # Choose a "nice" total length in display units that fits into max_px
        nice_bases = [1, 2, 5]
        best_len_du = None
        best_len_px = 0
        for exp in range(-3, 7):
            step = 10 ** exp
            for b in nice_bases:
                length_du = b * step
                length_px = length_du / du_per_px
                if 10 <= length_px <= max_px and length_px > best_len_px:
                    best_len_px = length_px
                    best_len_du = length_du
        if best_len_du is None:
            best_len_du = max_px * du_per_px
            best_len_px = max_px

        seg_px = best_len_px / total_segments

        # Bar geometry & styles
        bar_h = max(4, int(round(content.height() * 0.02)))
        tick_h = bar_h
        font_px = max(8, int(round(content.height() * 0.035)))
        margin = max(4, int(round(min(content.width(), content.height()) * 0.03)))

        pos = (self._scale_bar_position or "Bottom Left").lower()
        bw = int(round(best_len_px))
        bh = bar_h
        if "top" in pos:
            by = int(content.y() + margin)
            text_above = False
        else:
            by = int(content.y() + content.height() - margin - bh)
            text_above = True
        if "right" in pos:
            bx = int(content.x() + content.width() - margin - bw)
        else:
            bx = int(content.x() + margin)

        # Prepare painter
        p = QPainter(img)
        p.setRenderHints(QPainter.Antialiasing | QPainter.TextAntialiasing, on=True)
        pen = QColor(0, 0, 0)
        brush = QColor(0, 0, 0)
        p.setPen(pen)

        # Compute label text now (needed for background bounds)
        font = p.font()
        font.setPointSizeF(font_px * 0.75)
        p.setFont(font)
        label = f"{self._format_distance(best_len_du)} {unit_label}"
        metrics = p.fontMetrics()
        text_w = metrics.horizontalAdvance(label)
        text_h = metrics.height()
        if text_above:
            tx = bx + bw - text_w
            ty = by - 2
            label_rect = QRectF(tx, ty - (text_h - metrics.ascent()), text_w, text_h)  # approx ascent baseline shift
        else:
            tx = bx + bw - text_w
            ty = by + bh + text_h
            label_rect = QRectF(tx, by + bh, text_w, text_h)

        bar_rect = QRectF(bx, by, bw, bh)

        # ---- Optional white background behind bar + label ----
        white_bg = False
        cb = getattr(self.dlg, "sbWhiteBg", None)
        if cb is not None and cb.isChecked():
            white_bg = True

        if white_bg:
            # Union of bar and label rects, with padding
            union = bar_rect.united(label_rect)
            bg_pad = max(3, int(round(min(content.width(), content.height()) * 0.01)))
            bg_rect = QRectF(
                union.x() - bg_pad,
                union.y() - bg_pad,
                union.width() + 2 * bg_pad,
                union.height() + 2 * bg_pad
            )
            # Clamp to content rect (keep the bg inside the map content)
            bg_rect = bg_rect.intersected(content)

            # Slightly translucent white with light border for readability
            p.fillRect(bg_rect, QColor(255, 255, 255, 230))
            p.setPen(QColor(0, 0, 0, 60))
            p.drawRect(bg_rect)
            p.setPen(pen)  # restore solid black for bar and ticks

        # ---- Draw bar ----
        if self._scale_bar_style == "Single Box":
            y_top = by
            left_segments = self._scale_bar_segments_left
            right_segments = self._scale_bar_segments_right
            if right_segments == left_segments:
                seg_px_left = seg_px
                seg_px_right = seg_px
            else:
                seg_px_left = (best_len_px / 2) / left_segments
                seg_px_right = (best_len_px / 2) / right_segments

            for i in range(left_segments):
                x0 = bx + int(round(i * seg_px_left))
                x1 = bx + int(round((i + 1) * seg_px_left))
                w = max(1, x1 - x0)
                rect = QRectF(x0, y_top, w, bh)
                if i % 2 == 0:
                    p.fillRect(rect, brush)
                    rect_filled = True
                else:
                    p.drawRect(rect)
                    rect_filled = False

            for i in range(right_segments):
                x0 = bx + int(round((left_segments * seg_px_left) + i * seg_px_right))
                x1 = bx + int(round((left_segments * seg_px_left) + (i + 1) * seg_px_right))
                w = max(1, x1 - x0)
                rect = QRectF(x0, y_top, w, bh)
                if rect_filled:
                    p.drawRect(rect)
                    rect_filled = False
                else:
                    p.fillRect(rect, brush)
                    rect_filled = True

            p.drawRect(QRectF(bx, y_top, bw, bh))

        elif self._scale_bar_style == "Double Box":
            y_top = by
            half_bar_h = bh // 2
            for i in range(total_segments):
                x0 = bx + int(round(i * seg_px))
                x1 = bx + int(round((i + 1) * seg_px))
                w = max(1, x1 - x0)
                rect_bottom = QRectF(x0, y_top + half_bar_h, w, half_bar_h)
                rect_top = QRectF(x0, y_top, w, half_bar_h)
                if i % 2 == 0:
                    p.fillRect(rect_bottom, brush)
                    p.drawRect(rect_top)
                else:
                    p.fillRect(rect_top, brush)
                    p.drawRect(rect_bottom)

        elif self._scale_bar_style == "Line Ticks Middle":
            y_mid = by + bh // 2
            p.drawLine(int(bx), y_mid, int(bx + bw), y_mid)
            for i in range(total_segments + 1):
                x = int(bx + i * seg_px)
                p.drawLine(x, y_mid - tick_h // 2, x, y_mid + tick_h // 2)

        # ---- Draw label ----
        p.drawText(int(tx), int(ty), label)

        p.end()

    def _format_distance(self, val):
        """Nice formatting for scale bar labels."""
        if val >= 1000:
            return f"{val:,.0f}"
        if val >= 100:
            return f"{val:,.0f}"
        if val >= 10:
            return f"{val:,.1f}"
        if val >= 1:
            return f"{val:,.2f}"
        return f"{val:.2g}"

    def _scale_bar_unit_factor(self):
        """
        Returns (factor, label) where:
          displayed_value = map_units * factor
        """
        # Destination CRS of canvas / export
        dest_crs = self.iface.mapCanvas().mapSettings().destinationCrs()
        map_unit = dest_crs.mapUnits()  # QgsUnitTypes.DistanceUnit

        mode = self._scale_bar_units_mode

        # Project units: show native map units
        if mode == "Project":
            return 1.0, QgsUnitTypes.toAbbreviatedString(map_unit)

        # Target units
        if mode == "m":
            target = QgsUnitTypes.DistanceMeters
            label = "m"
        elif mode == "km":
            target = QgsUnitTypes.DistanceKilometers
            label = "km"
        elif mode == "ft":
            target = QgsUnitTypes.DistanceFeet
            label = "ft"
        elif mode == "mi":
            target = QgsUnitTypes.DistanceMiles
            label = "mi"
        else:
            # Fallback to project units
            return 1.0, QgsUnitTypes.toAbbreviatedString(map_unit)

        factor = QgsUnitTypes.fromUnitToUnitFactor(map_unit, target)
        return factor, label

    def _on_scale_bar_style_changed(self, idx: int):
        combo = getattr(self.dlg, "comboScaleBar", None)
        if combo is None:
            return
        self._scale_bar_style = combo.currentText()
        self._render_preview_current_extent()

    def _on_scale_bar_units_changed(self, idx: int):
        combo = getattr(self.dlg, "comboScaleUnits", None)
        if combo is None:
            return
        self._scale_bar_units_mode = combo.currentText()
        self._render_preview_current_extent()

    def _on_scale_bar_segments_changed(self, value: int):
        spin_left = getattr(self.dlg, "spinScaleSegmentsLeft", None)
        spin_right = getattr(self.dlg, "spinScaleSegmentsRight", None)
        if spin_left is not None:
            self._scale_bar_segments_left = max(1, int(spin_left.value()))
        if spin_right is not None:
            self._scale_bar_segments_right = max(0, int(spin_right.value()))
        self._render_preview_current_extent()

    def _on_scale_bar_position_changed(self, idx: int):
        pos_label = self.dlg.comboScaleBarPosition.currentText().strip()
        # Normalize to our four options (fallback to Top Left)
        allowed = {"Top Left", "Top Right", "Bottom Right", "Bottom Left"}
        if pos_label in allowed:
            self._scale_bar_position = pos_label
            self._render_preview_current_extent()

    def _draw_north_arrow_on_preview(self, full_img):
        """
        Draw the selected north arrow SVG onto 'full_img', positioned and scaled
        relative to the *map content* (the chosen extent), not the whole preview.
        """
        if self._northPreviewLabel is None:
            return
        if not self._north_arrow_svg_path:
            return

        content = self._preview_content_rect()
        if content.width() < 2 or content.height() < 2:
            return

        renderer = QSvgRenderer(self._north_arrow_svg_path)
        if not renderer.isValid():
            return

        # Base size = % of the *shorter* side of the map content
        shorter = min(content.width(), content.height())
        base = max(1, int(round(shorter * (self._north_arrow_scale_pct / 100.0))))

        # SVG aspect using viewBox if available
        vb = renderer.viewBoxF()
        if not vb.isNull() and vb.width() > 0 and vb.height() > 0:
            vb_w, vb_h = vb.width(), vb.height()
        else:
            ds = renderer.defaultSize()
            vb_w = max(1.0, float(ds.width()))
            vb_h = max(1.0, float(ds.height()))

        # Maintain aspect so the larger edge equals 'base'
        if vb_w >= vb_h:
            tgt_w = base
            tgt_h = max(1, int(round(base * (vb_h / vb_w))))
        else:
            tgt_h = base
            tgt_w = max(1, int(round(base * (vb_w / vb_h))))

        # Margin from map-content edges
        margin = max(4, int(round(shorter * 0.02)))

        # Position inside the *content* rect
        pos = (self._north_arrow_position or "Top Left").lower()
        if "top" in pos and "left" in pos:
            x = content.x() + margin
            y = content.y() + margin
        elif "top" in pos and "right" in pos:
            x = content.x() + content.width() - tgt_w - margin
            y = content.y() + margin
        elif "bottom" in pos and "right" in pos:
            x = content.x() + content.width() - tgt_w - margin
            y = content.y() + content.height() - tgt_h - margin
        else:  # Bottom Left
            x = content.x() + margin
            y = content.y() + content.height() - tgt_h - margin

        # Render onto 'full_img'
        p = QPainter(full_img)
        p.setRenderHints(QPainter.Antialiasing | QPainter.SmoothPixmapTransform | QPainter.TextAntialiasing, on=True)
        renderer.render(p, QRectF(x, y, tgt_w, tgt_h))
        p.end()

    def _on_north_arrow_style_changed(self, idx: int):
        combo = self.dlg.comboNorthArrowStyle
        self._north_arrow_svg_path = combo.itemData(idx)  # full path or None
        # Update small icon preview (if you added it earlier)
        self._update_north_arrow_preview()
        # Re-render map preview with arrow
        self._render_preview_current_extent()

    def _on_north_arrow_position_changed(self, idx: int):
        text = self.dlg.comboNorthArrowPosition.currentText().strip()
        # Normalize to our four options (fallback to Top Left)
        allowed = {"Top Left", "Top Right", "Bottom Right", "Bottom Left"}
        self._north_arrow_position = text if text in allowed else "Top Left"
        self._render_preview_current_extent()

    def _on_north_arrow_scale_changed(self, value: int):
        self._north_arrow_scale_pct = int(value)
        self._render_preview_current_extent()

    def _populate_north_arrows_dropdown(self):
        """
        Scan QGIS SVG paths for likely north-arrow/compass SVGs and fill comboNorthArrowStyle.
        Stores full SVG path in itemData; shows a small icon + human name as text.
        """
        combo = getattr(self.dlg, "comboNorthArrowStyle", None)
        if combo is None:
            return

        combo.blockSignals(True)
        combo.clear()
        combo.addItem("None", None)  # first option

        # Collect candidates from all SVG search paths
        svg_dirs = QgsApplication.svgPaths()  # list of directories
        want = []
        seen = set()

        # Heuristics: include files/folders with these tokens
        tokens = ("north", "arrow", "compass", "rose")

        def looks_like_north_arrow(path_lower: str) -> bool:
            return any(tok in path_lower for tok in tokens)

        for base in svg_dirs:
            if not base:
                continue
            it = QDir(base)
            # Recurse to find all .svg files
            stack = [base]
            while stack:
                d = stack.pop()
                qd = QDir(d)
                # subdirs
                for sub in qd.entryList(QDir.Dirs | QDir.NoDotAndDotDot):
                    stack.append(qd.filePath(sub))
                # files
                for fn in qd.entryList(["*.svg"], QDir.Files):
                    full = qd.filePath(fn)
                    key = full.lower()
                    if key in seen:
                        continue
                    seen.add(key)
                    if looks_like_north_arrow(key):
                        want.append(full)

        # Sort by filename for a stable UX
        want.sort(key=lambda p: p.split("/")[-1].lower())

        # Build icons and names
        icon_size = QSize(48, 48)  # reasonable combo icon size
        for path in want:
            name = path.split("/")[-1]  # filename
            display = name.rsplit(".", 1)[0]  # strip .svg
            # Render a small icon thumbnail
            pix = QPixmap(icon_size)
            pix.fill(Qt.transparent)
            try:
                r = QSvgRenderer(path)
                if r.isValid():
                    painter = QPainter(pix)
                    r.render(painter)
                    painter.end()
                    icon = QIcon(pix)
                else:
                    icon = QIcon()  # fallback: no icon
            except Exception:
                icon = QIcon()
            combo.addItem(icon, display, path)

        # Restore previous selection if any
        if self._north_arrow_svg_path:
            idx = combo.findData(self._north_arrow_svg_path)
            if idx >= 0:
                combo.setCurrentIndex(idx)
        combo.blockSignals(False)

    def eventFilter(self, obj, ev):
        if obj is getattr(self, "arrowWidget", None) and ev.type() == QEvent.Resize:
            # call back into the plugin via a function the plugin set on the dialog
            if hasattr(self, "_onArrowWidgetResized"):
                self._onArrowWidgetResized()
        return super().eventFilter(obj, ev)

    def _preview_content_rect(self) -> QRectF:
        """
        Returns the QRectF (x, y, w, h) of the *map content* inside the preview image,
        i.e., the region where the chosen extent is rendered (excluding padding).
        """
        if self._custom_extent is None or self._custom_extent.height() == 0:
            return QRectF(0, 0, 0, 0)

        # Full preview label size (what 'full' image is)
        size = self._previewLabel.size()
        W, H = max(1, size.width()), max(1, size.height())

        # Aspect ratios
        rect = self._custom_extent
        map_ratio = rect.width() / rect.height() if rect.height() != 0 else 1.0
        widget_ratio = W / H if H != 0 else 1.0

        # Compute map image size that fits INSIDE the widget without cropping
        if map_ratio >= widget_ratio:
            map_w = W
            map_h = int(round(W / map_ratio))
        else:
            map_h = H
            map_w = int(round(H * map_ratio))

        # Centered content origin
        x0 = (W - map_w) // 2
        y0 = (H - map_h) // 2

        return QRectF(x0, y0, map_w, map_h)

    def _update_north_arrow_preview(self):
        """Render the selected SVG into arrowWidget (or its child label) without overflow."""
        lbl = self._northPreviewLabel
        if lbl is None:
            return

        lbl.clear()
        path = self._north_arrow_svg_path
        if not path:
            lbl.setText("None")
            return

        renderer = QSvgRenderer(path)
        if not renderer.isValid():
            lbl.setText("Invalid")
            return

        # Logical size of the label (Qt coords; independent of devicePixelRatio)
        size = lbl.size()
        W, H = max(1, size.width()), max(1, size.height())

        # Transparent pixmap to draw into
        pix = QPixmap(W, H)
        pix.fill(Qt.transparent)

        # Prefer the SVG viewBox to compute aspect safely
        vb = renderer.viewBoxF()  # QRectF
        if vb.isNull() or vb.width() <= 0 or vb.height() <= 0:
            # Fallback to defaultSize if viewBox is missing
            ds = renderer.defaultSize()
            vb_w = max(1.0, float(ds.width()))
            vb_h = max(1.0, float(ds.height()))
        else:
            vb_w = vb.width()
            vb_h = vb.height()

        # Add a tiny inner margin to avoid antialias bleed & stroke overhang
        # (also helps when layout adds 1px border)
        margin = max(1, int(round(min(W, H) * 0.03)))  # ~3% of shorter side, at least 1px
        avail_w = max(1, W - 2 * margin)
        avail_h = max(1, H - 2 * margin)

        # Scale to fit while preserving aspect ratio (no overflow)
        sx = avail_w / vb_w
        sy = avail_h / vb_h
        scale = min(sx, sy)

        # Compute final integer target size, clamp to available space
        tgt_w = int(scale * vb_w)
        tgt_h = int(scale * vb_h)
        tgt_w = min(tgt_w, avail_w)
        tgt_h = min(tgt_h, avail_h)

        # Center inside the label with the margin applied
        x = (W - tgt_w) // 2
        y = (H - tgt_h) // 2
        target = QRectF(x, y, tgt_w, tgt_h)

        # Render with antialiasing
        p = QPainter(pix)
        p.setRenderHints(
            QPainter.Antialiasing |
            QPainter.TextAntialiasing |
            QPainter.SmoothPixmapTransform,
            on=True
        )
        renderer.render(p, target)
        p.end()
        lbl.setPixmap(pix)

    def _composite_north_arrow_on_image(self, img: QImage):
        """Draw the selected north-arrow SVG onto 'img' in-place.
           Placement is relative to the *map content* (here it's the FULL export image)."""
        if not getattr(self, "_north_arrow_svg_path", None):
            return  # nothing to draw

        W, H = img.width(), img.height()
        if W <= 1 or H <= 1:
            return

        renderer = QSvgRenderer(self._north_arrow_svg_path)
        if not renderer.isValid():
            return

        # Size: percentage of the shorter side (from horizontalSlider_2)
        pct = int(getattr(self, "_north_arrow_scale_pct", 18))
        shorter = min(W, H)
        base = max(1, int(round(shorter * (pct / 100.0))))

        # Resolve SVG aspect from viewBox/defaultSize
        vb = renderer.viewBoxF()
        if not vb.isNull() and vb.width() > 0 and vb.height() > 0:
            vb_w, vb_h = vb.width(), vb.height()
        else:
            ds = renderer.defaultSize()
            vb_w = max(1.0, float(ds.width()))
            vb_h = max(1.0, float(ds.height()))

        # Keep aspect: larger edge == base
        if vb_w >= vb_h:
            tgt_w = base
            tgt_h = max(1, int(round(base * (vb_h / vb_w))))
        else:
            tgt_h = base
            tgt_w = max(1, int(round(base * (vb_w / vb_h))))

        # Margin from edges
        margin = max(4, int(round(shorter * 0.02)))

        # Position inside full image (export has no letterboxing)
        pos = (getattr(self, "_north_arrow_position", "Top Left") or "Top Left").lower()
        if "top" in pos and "left" in pos:
            x, y = margin, margin
        elif "top" in pos and "right" in pos:
            x, y = W - tgt_w - margin, margin
        elif "bottom" in pos and "right" in pos:
            x, y = W - tgt_w - margin, H - tgt_h - margin
        else:  # Bottom Left (default)
            x, y = margin, H - tgt_h - margin

        p = QPainter(img)
        p.setRenderHints(QPainter.Antialiasing | QPainter.SmoothPixmapTransform | QPainter.TextAntialiasing, on=True)
        renderer.render(p, QRectF(x, y, tgt_w, tgt_h))
        p.end()

    def _export(self):
        # --- 1) Validate inputs ---
        if self._custom_extent is None:
            QMessageBox.warning(self.dlg, "No extent", "Please choose an extent first.")
            return
        if self._custom_extent.width() <= 0 or self._custom_extent.height() <= 0:
            QMessageBox.warning(self.dlg, "Invalid extent", "The chosen extent is invalid.")
            return

        width_px = int(self.dlg.spinWidth.value())
        height_px = int(self.dlg.spinHeigth.value())
        if width_px <= 0 or height_px <= 0:
            QMessageBox.warning(self.dlg, "Invalid size", "Width and height must be positive integers.")
            return

        # --- 2) Ask save path & format ---
        default_name = f"{QgsProject.instance().baseName() or 'map'}_{width_px}x{height_px}"
        filters = "PNG (*.png);;JPEG (*.jpg *.jpeg);;TIFF (*.tif *.tiff);;WEBP (*.webp)"
        out_fp, selected_filter = QFileDialog.getSaveFileName(self.dlg, "Export map image", default_name, filters)
        if not out_fp:
            return

        # Decide format from extension or selected filter
        ext = out_fp.lower().split('.')[-1] if '.' in out_fp else ''
        ext_to_fmt = {"png": "PNG", "jpg": "JPEG", "jpeg": "JPEG", "tif": "TIFF", "tiff": "TIFF", "webp": "WEBP"}
        fmt = ext_to_fmt.get(ext, None)
        if fmt is None:
            # no extension → infer from selected filter and append extension
            if "PNG" in selected_filter:
                fmt, out_fp = "PNG", out_fp + ".png"
            elif "JPEG" in selected_filter:
                fmt, out_fp = "JPEG", out_fp + ".jpg"
            elif "TIFF" in selected_filter:
                fmt, out_fp = "TIFF", out_fp + ".tif"
            elif "WEBP" in selected_filter:
                fmt, out_fp = "WEBP", out_fp + ".webp"
            else:
                fmt, out_fp = "PNG", out_fp + ".png"

        transparent = bool(self.dlg.chkTransparent.isChecked())

        # --- 3) Render map (only the picked extent) to QImage ---
        canvas = self.iface.mapCanvas()

        ms = QgsMapSettings()
        ms.setLayers(canvas.layers())  # same layer stack
        ms.setDestinationCrs(canvas.mapSettings().destinationCrs())  # same dest CRS
        ms.setOutputSize(QSize(width_px, height_px))
        ms.setOutputDpi(96)  # pixel-accurate; DPI not critical when size is in px
        ms.setBackgroundColor(QColor(255, 255, 255, 0 if transparent else 255))
        ms.setExtent(QgsRectangle(self._custom_extent))  # ← the chosen area
        ms.setRotation(canvas.rotation())  # match canvas rotation

        job = QgsMapRendererParallelJob(ms)
        job.start()
        job.waitForFinished()
        img = job.renderedImage()  # QImage with alpha if transparent=True

        # Add all extra branding elements here (logo, scale bar, north arrow, footer text):
        self._composite_north_arrow_on_image(img)

        # Scale bar on export: full image is the map content
        self._draw_scale_bar(img, QRectF(0, 0, width_px, height_px), self._custom_extent.width())


        # --- 4) JPEG doesn't support alpha → flatten if needed ---
        if fmt == "JPEG" and transparent:
            flat = QImage(width_px, height_px, QImage.Format_RGB32)
            flat.fill(QColor(255, 255, 255))  # white background
            p = QPainter(flat)
            p.drawImage(0, 0, img)
            p.end()
            img_to_save = flat
        else:
            img_to_save = img

        # --- 5) Save ---
        if not img_to_save.save(out_fp, fmt):
            QMessageBox.critical(self.dlg, "Export failed", f"Could not save image to:\n{out_fp}")
            return

        QMessageBox.information(self.dlg, "Export complete", f"Saved:\n{out_fp}")


    def _apply_dimensions(self, w: int, h: int, scale: int):
        """Set spinWidth, spinHeigth, sizeScaler without emitting valueChanged."""
        # Clamp to base limits (your 100% size)
        w = int(max(0, min(w, self._width_px)))
        h = int(max(0, min(h, self._height_px)))
        scale = int(max(0, min(scale, 100)))

        # Block signals while setting to avoid feedback loops
        bw = QSignalBlocker(self.dlg.spinWidth)
        bh = QSignalBlocker(self.dlg.spinHeigth)
        bs = QSignalBlocker(self.dlg.sizeScaler)

        self.dlg.spinWidth.setValue(w)
        self.dlg.spinHeigth.setValue(h)
        self.dlg.sizeScaler.setValue(scale)

    def _change_height(self):
        if self._custom_extent is None:
            return
        h = self.dlg.spinHeigth.value()
        h = min(h, self._height_px)
        w = int(round(h * (self._width_px / float(self._height_px))))
        scale = w * 100.0 / self._width_px
        self._apply_dimensions(w, h, scale)

    def _change_width(self):
        if self._custom_extent is None:
            return
        w = self.dlg.spinWidth.value()
        w = min(w, self._width_px)
        h = int(round(w * (self._height_px / float(self._width_px))))
        scale = w * 100.0 / self._width_px
        self._apply_dimensions(w, h, scale)

    def _change_width_height(self):
        if self._custom_extent is None:
            return
        current_value = self.dlg.sizeScaler.value()
        w = int(round(self._width_px * (current_value / 100.0)))
        h = int(round(self._height_px * (current_value / 100.0)))
        self._apply_dimensions(w, h, current_value)

    def _visualize_area_from_custom_extent(self):
        preview_container = self.dlg.widget
        if preview_container.layout() is None:
            preview_container.setLayout(QVBoxLayout(preview_container))

        if not hasattr(self, "_previewLabel"):
            self._previewLabel = QLabel(preview_container)
            self._previewLabel.setObjectName("lblPreview")
            self._previewLabel.setScaledContents(False)
            self._previewLabel.setMinimumSize(280, 180)
            self._previewLabel.setAlignment(Qt.AlignCenter)
            self._previewLabel.setText("Preview")
            self._previewLabel.setStyleSheet(
                "QLabel { border: 1px solid #999; background: #fff; }")
            preview_container.layout().addWidget(self._previewLabel)

    def _render_preview_current_extent(self):
        """Render self._custom_extent centered into the preview label with blank padding."""
        rect = self._custom_extent
        if rect is None or rect.width() <= 0 or rect.height() <= 0:
            return

        # 1) Preview widget size
        size = self._previewLabel.size()
        W, H = max(1, size.width()), max(1, size.height())

        # 2) Aspect ratios
        map_ratio = rect.width() / rect.height() if rect.height() != 0 else 1.0
        widget_ratio = W / H if H != 0 else 1.0

        # 3) Compute the map image size that fits INSIDE the widget without cropping
        if map_ratio >= widget_ratio:
            # map is wider → span full width, reduce height
            map_w = W
            map_h = int(round(W / map_ratio))
        else:
            # map is taller → span full height, reduce width
            map_h = H
            map_w = int(round(H * map_ratio))

        # 4) Render map into that smaller image (no extent manipulation)
        bg = QColor(255, 255, 255, 255)

        ms = QgsMapSettings()
        ms.setLayers(self.iface.mapCanvas().layers())
        ms.setDestinationCrs(self.iface.mapCanvas().mapSettings().destinationCrs())
        ms.setOutputSize(QSize(map_w, map_h))
        ms.setOutputDpi(96)  # low DPI is fine for preview
        ms.setBackgroundColor(bg)
        ms.setExtent(QgsRectangle(rect))  # DON'T expand/fit; preserve exact extent
        ms.setRotation(self.iface.mapCanvas().rotation())

        job = QgsMapRendererParallelJob(ms)

        def _on_finished():
            map_img = job.renderedImage()

            # 5) Composite into a full-size (W×H) image, centered (letterbox/pillarbox)
            full = QImage(W, H, QImage.Format_ARGB32_Premultiplied)
            full.fill(bg)
            painter = QPainter(full)
            x = (W - map_img.width()) // 2
            y = (H - map_img.height()) // 2
            painter.drawImage(x, y, map_img)
            painter.end()

            self._draw_north_arrow_on_preview(full)
            # draw scale bar based on preview content + extent
            content = self._preview_content_rect()
            self._draw_scale_bar(full, content, rect.width())

            self._previewLabel.setPixmap(QPixmap.fromImage(full))

        job.finished.connect(_on_finished)
        job.start()
        job.waitForFinished()
        self._set_width_height()

    def _initialize_size_scaler(self):
        self.dlg.spinWidth.setEnabled(False)
        self.dlg.spinHeigth.setEnabled(False)
        self.dlg.sizeScaler.setEnabled(False)

    def _set_width_height(self):
        if self._custom_extent is None:
            return
        self.dlg.spinWidth.setEnabled(True)
        self.dlg.spinHeigth.setEnabled(True)
        self.dlg.spinWidth.setValue(self._width_px)
        self.dlg.spinHeigth.setValue(self._height_px)
        self.dlg.sizeScaler.setEnabled(True)
        self.dlg.sizeScaler.setValue(100)

    def _setup_choose_extent_menu(self):
        menu = QMenu(self.dlg)
        act_canvas = QAction("From Canvas", self.dlg)
        act_draw = QAction("Draw manually", self.dlg)
        act_canvas.triggered.connect(self._choose_extent_from_canvas)
        act_draw.triggered.connect(self._choose_extent_draw)
        menu.addAction(act_canvas)
        menu.addAction(act_draw)
        # Make the toolbutton behave like QGIS tools do
        self.dlg.btnChooseExtent.setMenu(menu)
        self.dlg.btnChooseExtent.setPopupMode(QToolButton.MenuButtonPopup)
        self.dlg.btnChooseExtent.setDefaultAction(act_canvas)  # click button = From Canvas

    def _choose_extent_from_canvas(self):
        rect = self.iface.mapCanvas().extent()
        self._custom_extent = rect
        self._width_px = self.iface.mapCanvas().mapSettings().outputSize().width()
        self._height_px = self.iface.mapCanvas().mapSettings().outputSize().height()
        self.dlg.lineExtent.setText(f"{rect.toString(6)}")
        self._render_preview_current_extent()

    def _choose_extent_draw(self):
        # Hide dialog while we interact with the canvas
        self.dlg.hide()
        tool = ExtentPickerTool(self.iface.mapCanvas())
        # When user finishes, we’ll get a QRect in map (project CRS) coords
        def _picked(rect: QgsRectangle | None, width_px: int | None, height_px: int | None):
            # restore dialog first
            self.dlg.show()
            if rect is None:
                return
            self._custom_extent = rect
            self._width_px = width_px
            self._height_px = height_px
            self._render_preview_current_extent()

        tool.extentPicked.connect(_picked)
        self.iface.mapCanvas().setMapTool(tool)

    def _browse_logo(self):
        logo_path, _ = QtWidgets.QFileDialog.getOpenFileName(self.dlg, "Select Logo Image", "", "Image Files (*.png *.jpg *.bmp);;All Files (*)")
        if logo_path:
            self.dlg.lineLogoPath.setText(logo_path)

    def _close(self):
        self.dlg.close()